services:
  - type: web
    name: mishpachat-bit
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_lzWeA5f4RIUJ@ep-young-darkness-alnbgfe7.c-3.eu-central-1.aws.neon.tech/neondb?sslmode=require"
